ROB: Skip destination page being None in PdfWriter (#2963)
Some PDFs happen `dest["/Page"] is None` which causes 

> AttributeError: 'NoneType' object has no attribute 'indirect_reference'

when merging files.