ROB: Set ignore_eof=True for read_until_regex (#1521)
This was initially motivated by `NumberObject.read_from_stream`, which
was calling `read_until_regex` with the default value of
`ignore_eof=False` and thus raising exceptions like:

```
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```

https://github.com/py-pdf/PyPDF2/commit/431ba7092037af7d1c296f8f280aca167859ce61
demonstrates a similar fix for `NameObject.read_from_stream`.

The change to `NumberObject.read_from_stream` had now made
all callers of `read_until_regex` pass `ignore_eof=True`. For this reason,
it's cleaner to remove the parameter entirely and change the default behavior.