BUG: Handle cases where decodeParms is an ArrayObject (#405)
Fixes bug where decodeParms.get(...) causes
AttributeError: 'ArrayObject' object has no attribute 'get'

Closes #404