ROB: Deal with invalid Destinations (#1028)
Issue: An
        AttributeError: 'NoneType' object has no attribute 'get_object'
    was raised when trying to write a page that was merged.

Fix: Guard IndirectObject.get_object access

Closes #997